all:
	g++ -g -Wall ../Network/Network.cpp -I"../Network/" ../Chat/Chat.cpp -I"../Chat/"  ChatServer.cpp -o ChatServer -lws2_32

run:
	./ChatServer.exe
	
buildRun:
	g++ -g -Wall ../Network/Network.cpp -I"../Network/" ../Chat/Chat.cpp -I"../Chat/"  ChatServer.cpp -o ChatServer -lws2_32
	./ChatServer.exe