all:
	g++ -g -Wall ../Network/Network.cpp -I"../Network/" server.cpp -o server -lws2_32

run:
	./server.exe
	
buildRun:
	g++ -g -Wall ../Network/Network.cpp -I"../Network/" server.cpp -o server -lws2_32
	./app.exe